apiVersion: v1
kind: Pod
metadata:
  name: cole-serverapp
  labels:
     app: cole-serverapp
spec:
  nodeName: machine2
  containers:
  - image: 192.168.33.10:5000/cole-serverapp:v1.0.0
    name: cole-serverapp
    ports:
    - containerPort: 8080
      protocol: TCP
