apiVersion: v1
kind: Pod
metadata:
  name: serverapp
  labels:
     app: serverapp
spec:
  nodeName: machine2
  containers:
  - image: 192.168.33.10:5000/serverapp:v1.0.0
    name: serverapp
    ports:
    - containerPort: 8080
      protocol: TCP
