apiVersion: v1
kind: ReplicationController
metadata:
  name: cole-serverapp-rc
spec:
  replicas: 3
  selector:
    app: cole-serverapp
  template:
    metadata:
      labels:
        app: cole-serverapp
    spec:
      nodeName: machine2
      containers:
      - name: cole-serverapp
        image: 192.168.33.10:5000/cole-serverapp:v1.0.0
        ports:
        - containerPort: 8080
