apiVersion: v1
kind: ReplicationController
metadata:
  name: serverapp-rc
spec:
  replicas: 3
  selector:
    app: serverapp
  template:
    metadata:
      labels:
        app: serverapp
    spec:
      containers:
      - name: serverapp
        image: 192.168.33.10:5000/serverapp:v1.0.0
        ports:
        - containerPort: 8080
