apiVersion: v1
kind: Pod
metadata:
  name: cole-ubuntucurl
  labels:
     app: cole-ubuntucurl
spec:
  nodeName: machine3
  containers:
  - image: 192.168.33.10:5000/cole-ubuntucurl
    name: cole-ubuntucurl
    ports:
    - containerPort: 8080
      protocol: TCP
