apiVersion: v1
kind: Pod
metadata:
  name: ubuntucurl
  labels:
     app: ubuntucurl
spec:
  nodeName: machine3
  containers:
  - image: 192.168.33.10:5000/ubuntucurl
    name: ubuntucurl
    ports:
    - containerPort: 8080
      protocol: TCP
