version: "3.3"

services:

  server_app:
    build: ./server_app
    volumes:
      - ./server_app:/opt/server_app/src
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - ENDPOINT_MESSAGE=A very interesting message.
    ports:
      - "5555:80"
    expose:
      - "80"
    networks:
      my_network:
        ipv4_address: 172.18.0.2

  client_app:
    build: ./client_app
    volumes:
      - ./client_app:/opt/client_app/src
    environment:
      - PERIOD=2
      - PORT=80
      - HOST=172.18.0.2
      - REPITITIONS=10
    depends_on:
      - server_app
    networks:
      - my_network

networks:
  my_network:
    driver : bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
