# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  machine.vm.provision "file", source: "./client_app", destination: "$HOME/client_app"
  machine.vm.provision "file", source: "./server_app", destination: "$HOME/server_app"
  config.vm.provision "shell", privileged: true, inline:<<-SHELL
    apt-get -y update
    apt-get -y docker
    docker build -f /home/vagrant/server_app .
    docker build -f /home/vagrant/client_app .
  SHELL
end
