# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # require plugin https://github.com/leighmcculloch/vagrant-docker-compose
  config.vagrant.plugins = "vagrant-docker-compose"

  # install docker and docker-compose
  config.vm.provision :docker
  config.vm.provision :docker_compose

  config.vm.provision "file", source: "./docker-compose.yaml", destination: "$HOME/docker-compose.yaml"
  config.vm.provision "file", source: "./conf.d", destination: "$HOME/conf.d"
  config.vm.provision "file", source: "./client_app", destination: "$HOME/client_app"
  config.vm.provision "file", source: "./server_app", destination: "$HOME/server_app"
end
